const langData = {
  en: {
    home: "HOME",
    recycling: "RECYCLING",
    report: "REPORT",
    about: "ABOUT",
    myReports: "MY REPORTS",
    login: "LOGIN",
    signup: "SIGNUP",
    logout: "LOGOUT",
    welcome: "Welcome",

    heroTitle: "...",
    heroSubtitle: "...",
    recycleBtn: "...",
    reportBtn: "...",

    reportTitle: "Report Waste Issue",
    binId: "Dustbin ID",
    issueType: "Issue Type",
    selectIssue: "Select Issue Type",
    selectIssueDesc: "Please choose the problem type.",

    illegal: "Illegal Dumping",
    overflow: "Overflowing Bin",
    damaged: "Damaged Bin",

    location: "GPS Location",
    phone: "Contact Number",
    phonePlaceholder: "Enter phone number",
    descPlaceholder: "Describe the issue...",
    upload: "Upload Photo",
    submit: "Submit Report",
    submitting: "Submitting...",
    success: "Report Submitted",
    successDesc: "Thank you for helping keep the city clean!",
    fail: "Submission Failed",
    error: "Something went wrong",
    serverError: "Server Error",
    serverErrorDesc: "Unable to submit report",

    myDashboard: "My Dashboard",
    coins: "Coins Earned",
    submitted: "Reports Submitted",
    completed: "Reports Completed",
    rewards: "Redeem Rewards",
    redeem: "Redeem & Download Certificate",
    loginFirst: "Please login first",
    notEnoughCoins: "Not enough coins",
    redeemed: "Reward Redeemed"
  },

  hi: {
    home: "होम",
    recycling: "रीसाइक्लिंग",
    report: "रिपोर्ट",
    about: "अबाउट",
    myReports: "मेरी रिपोर्ट्स",
    login: "लॉगिन",
    signup: "साइन अप",
    logout: "लॉगआउट",
    welcome: "स्वागत",

    heroTitle:
      "स्वच्छता कोई कानून द्वारा थोपी गई जिम्मेदारी नहीं है, बल्कि समाज के प्रति हमारी जिम्मेदारी है।",
    heroSubtitle:
      "आज की छोटी कार्रवाई कल को साफ बनाती है।",
    recycleBtn: "रीसाइक्लिंग आइडियाज",
    reportBtn: "रिपोर्ट करें",
    reportTitle: "कचरा समस्या रिपोर्ट करें",
binId: "डस्टबिन आईडी",
issueType: "समस्या प्रकार",
selectIssue: "समस्या चुनें",
selectIssueDesc: "कृपया समस्या प्रकार चुनें",
illegal: "अवैध कचरा फेंकना",
overflow: "भरा हुआ डस्टबिन",
damaged: "टूटा हुआ डस्टबिन",
location: "जीपीएस लोकेशन",
phone: "संपर्क नंबर",
phonePlaceholder: "फोन नंबर दर्ज करें",
descPlaceholder: "समस्या का विवरण दें...",
upload: "फोटो अपलोड करें",
submit: "रिपोर्ट सबमिट करें",
submitting: "सबमिट हो रहा है...",
success: "रिपोर्ट सफलतापूर्वक भेजी गई",
successDesc: "शहर को साफ रखने में मदद के लिए धन्यवाद!",
fail: "सबमिशन असफल",
error: "कुछ गलत हुआ",
serverError: "सर्वर त्रुटि",
serverErrorDesc: "रिपोर्ट भेजने में असमर्थ",
myDashboard: "मेरा डैशबोर्ड",
coins: "कमाए गए कॉइन्स",
submitted: "सबमिट की गई रिपोर्ट्स",
completed: "पूर्ण हुई रिपोर्ट्स",
rewards: "रिवॉर्ड रिडीम करें",
redeem: "रिडीम करें और सर्टिफिकेट डाउनलोड करें",
loginFirst: "कृपया पहले लॉगिन करें",
notEnoughCoins: "पर्याप्त कॉइन्स नहीं हैं",
redeemed: "रिवॉर्ड सफलतापूर्वक रिडीम किया गया"
  },

  bn: {
    home: "হোম",
    recycling: "রিসাইক্লিং",
    report: "রিপোর্ট",
    about: "সম্পর্কে",
    myReports: "আমার রিপোর্ট",
    login: "লগইন",
    signup: "সাইন আপ",
    logout: "লগআউট",
    welcome: "স্বাগতম",

    heroTitle:
      "পরিষ্কার-পরিচ্ছন্নতা কোনো আইন দ্বারা চাপিয়ে দেওয়া দায়িত্ব নয়, বরং সমাজের প্রতি আমাদের দায়িত্ব।",
    heroSubtitle:
      "আজকের ছোট কাজ আগামীকালকে পরিষ্কার করে।",
    recycleBtn: "রিসাইক্লিং আইডিয়া",
    reportBtn: "রিপোর্ট",
    reportTitle: "বর্জ্য সমস্যা রিপোর্ট করুন",
binId: "ডাস্টবিন আইডি",
issueType: "সমস্যার ধরন",
selectIssue: "সমস্যা নির্বাচন করুন",
selectIssueDesc: "দয়া করে সমস্যার ধরন নির্বাচন করুন",
illegal: "অবৈধ আবর্জনা ফেলা",
overflow: "ভর্তি ডাস্টবিন",
damaged: "নষ্ট ডাস্টবিন",
location: "জিপিএস লোকেশন",
phone: "যোগাযোগ নম্বর",
phonePlaceholder: "ফোন নম্বর লিখুন",
descPlaceholder: "সমস্যার বর্ণনা দিন...",
upload: "ছবি আপলোড করুন",
submit: "রিপোর্ট জমা দিন",
submitting: "জমা হচ্ছে...",
success: "রিপোর্ট সফলভাবে জমা হয়েছে",
successDesc: "শহর পরিষ্কার রাখতে সাহায্যের জন্য ধন্যবাদ!",
fail: "জমা ব্যর্থ",
error: "কিছু ভুল হয়েছে",
serverError: "সার্ভার ত্রুটি",
serverErrorDesc: "রিপোর্ট পাঠানো যায়নি",
myDashboard: "আমার ড্যাশবোর্ড",
coins: "অর্জিত কয়েন",
submitted: "জমা দেওয়া রিপোর্ট",
completed: "সম্পন্ন রিপোর্ট",
rewards: "রিওয়ার্ড গ্রহণ করুন",
redeem: "রিডিম করে সার্টিফিকেট ডাউনলোড করুন",
loginFirst: "দয়া করে আগে লগইন করুন",
notEnoughCoins: "পর্যাপ্ত কয়েন নেই",
redeemed: "রিওয়ার্ড সফলভাবে গ্রহণ করা হয়েছে"
  },

  ta: {
    home: "முகப்பு",
    recycling: "மறுசுழற்சி",
    report: "அறிக்கை",
    about: "பற்றி",
    myReports: "என் அறிக்கைகள்",
    login: "உள்நுழை",
    signup: "பதிவு",
    logout: "வெளியேறு",
    welcome: "வரவேற்கிறோம்",

    heroTitle:
      "சுத்தம் என்பது சட்டம் விதித்த கடமை அல்ல, சமூகத்திற்கு நாம் கடமைப்பட்ட பொறுப்பு.",
    heroSubtitle:
      "இன்றைய சிறிய செயல் நாளைய சுத்தமான உலகை உருவாக்கும்.",
    recycleBtn: "மறுசுழற்சி யோசனைகள்",
    reportBtn: "அறிக்கை",
    reportTitle: "கழிவு பிரச்சினையை புகாரளிக்கவும்",
binId: "டஸ்ட்பின் ஐடி",
issueType: "பிரச்சனை வகை",
selectIssue: "பிரச்சனை தேர்ந்தெடுக்கவும்",
selectIssueDesc: "பிரச்சனை வகையை தேர்வு செய்யவும்",
illegal: "அனுமதியற்ற குப்பை கொட்டுதல்",
overflow: "நிரம்பிய டஸ்ட்பின்",
damaged: "சேதமடைந்த டஸ்ட்பின்",
location: "ஜிபிஎஸ் இடம்",
phone: "தொடர்பு எண்",
phonePlaceholder: "தொலைபேசி எண்ணை உள்ளிடவும்",
descPlaceholder: "பிரச்சனையை விவரிக்கவும்...",
upload: "புகைப்படத்தை பதிவேற்றவும்",
submit: "புகாரை சமர்ப்பிக்கவும்",
submitting: "சமர்ப்பிக்கப்படுகிறது...",
success: "புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது",
successDesc: "நகரத்தை சுத்தமாக வைத்திருக்க உதவியதற்கு நன்றி!",
fail: "சமர்ப்பிப்பு தோல்வி",
error: "ஏதோ தவறு நடந்தது",
serverError: "சர்வர் பிழை",
serverErrorDesc: "புகாரை அனுப்ப முடியவில்லை",
myDashboard: "என் டாஷ்போர்டு",
coins: "சம்பாதித்த நாணயங்கள்",
submitted: "சமர்ப்பிக்கப்பட்ட அறிக்கைகள்",
completed: "முடிக்கப்பட்ட அறிக்கைகள்",
rewards: "விருதுகளை பெறுங்கள்",
redeem: "பரிசை பெறவும் மற்றும் சான்றிதழை பதிவிறக்கவும்",
loginFirst: "முதலில் உள்நுழையவும்",
notEnoughCoins: "போதுமான நாணயங்கள் இல்லை",
redeemed: "விருது வெற்றிகரமாக பெறப்பட்டது"
  },

  te: {
    home: "హోమ్",
    recycling: "రీసైక్లింగ్",
    report: "రిపోర్ట్",
    about: "గురించి",
    myReports: "నా రిపోర్ట్స్",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    logout: "లాగౌట్",
    welcome: "స్వాగతం",

    heroTitle:
      "శుభ్రత అనేది చట్టం విధించిన బాధ్యత కాదు, సమాజానికి మన బాధ్యత.",
    heroSubtitle:
      "ఈ రోజు చిన్న చర్య రేపు శుభ్రమైన ప్రపంచాన్ని సృష్టిస్తుంది.",
    recycleBtn: "రీసైక్లింగ్ ఐడియాస్",
    reportBtn: "రిపోర్ట్",
    reportTitle: "వ్యర్థ సమస్యను నివేదించండి",
binId: "డస్ట్‌బిన్ ఐడి",
issueType: "సమస్య రకం",
selectIssue: "సమస్యను ఎంచుకోండి",
selectIssueDesc: "దయచేసి సమస్య రకం ఎంచుకోండి",
illegal: "అక్రమంగా చెత్త వేయడం",
overflow: "పూర్తిగా నిండిన బిన్",
damaged: "పాడైన బిన్",
location: "జీపీఎస్ స్థానం",
phone: "ఫోన్ నంబర్",
phonePlaceholder: "ఫోన్ నంబర్ నమోదు చేయండి",
descPlaceholder: "సమస్య వివరించండి...",
upload: "ఫోటో అప్‌లోడ్ చేయండి",
submit: "నివేదిక పంపండి",
submitting: "పంపుతోంది...",
success: "నివేదిక విజయవంతంగా పంపబడింది",
successDesc: "నగరాన్ని శుభ్రంగా ఉంచడంలో సహాయం చేసినందుకు ధన్యవాదాలు!",
fail: "పంపడం విఫలమైంది",
error: "ఏదో తప్పు జరిగింది",
serverError: "సర్వర్ లోపం",
serverErrorDesc: "నివేదిక పంపలేకపోయాం",
myDashboard: "నా డాష్‌బోర్డ్",
coins: "సంపాదించిన నాణేలు",
submitted: "సమర్పించిన నివేదికలు",
completed: "పూర్తయిన నివేదికలు",
rewards: "బహుమతులు పొందండి",
redeem: "రిడీమ్ చేసి సర్టిఫికేట్ డౌన్‌లోడ్ చేయండి",
loginFirst: "దయచేసి ముందుగా లాగిన్ అవ్వండి",
notEnoughCoins: "తగినన్ని నాణేలు లేవు",
redeemed: "బహుమతి విజయవంతంగా పొందబడింది"
  },

  mr: {
    home: "होम",
    recycling: "रीसायकलिंग",
    report: "रिपोर्ट",
    about: "बद्दल",
    myReports: "माझे रिपोर्ट्स",
    login: "लॉगिन",
    signup: "साइनअप",
    logout: "लॉगआउट",
    welcome: "स्वागत",

    heroTitle:
      "स्वच्छता ही कायद्याने लादलेली जबाबदारी नसून समाजाप्रती आपली जबाबदारी आहे.",
    heroSubtitle:
      "आजची छोटी कृती उद्याचा स्वच्छ जग निर्माण करते.",
    recycleBtn: "रीसायकलिंग कल्पना",
    reportBtn: "रिपोर्ट",
    reportTitle: "कचरा समस्या नोंदवा",
binId: "डस्टबिन आयडी",
issueType: "समस्या प्रकार",
selectIssue: "समस्या निवडा",
selectIssueDesc: "कृपया समस्या प्रकार निवडा",
illegal: "बेकायदेशीर कचरा टाकणे",
overflow: "भरलेला डस्टबिन",
damaged: "तुटलेला डस्टबिन",
location: "जीपीएस स्थान",
phone: "संपर्क क्रमांक",
phonePlaceholder: "फोन नंबर टाका",
descPlaceholder: "समस्येचे वर्णन करा...",
upload: "फोटो अपलोड करा",
submit: "रिपोर्ट सबमिट करा",
submitting: "सबमिट होत आहे...",
success: "रिपोर्ट यशस्वीरित्या सबमिट झाला",
successDesc: "शहर स्वच्छ ठेवण्यासाठी मदत केल्याबद्दल धन्यवाद!",
fail: "सबमिशन अयशस्वी",
error: "काहीतरी चूक झाली",
serverError: "सर्व्हर त्रुटी",
serverErrorDesc: "रिपोर्ट सबमिट करता आला नाही",
reportTitle: "कचरा समस्या नोंदवा",
binId: "डस्टबिन आयडी",
issueType: "समस्या प्रकार",
selectIssue: "समस्या निवडा",
selectIssueDesc: "कृपया समस्या प्रकार निवडा",
illegal: "बेकायदेशीर कचरा टाकणे",
overflow: "भरलेला डस्टबिन",
damaged: "तुटलेला डस्टबिन",
location: "जीपीएस स्थान",
phone: "संपर्क क्रमांक",
phonePlaceholder: "फोन नंबर टाका",
descPlaceholder: "समस्येचे वर्णन करा...",
upload: "फोटो अपलोड करा",
submit: "रिपोर्ट सबमिट करा",
submitting: "सबमिट होत आहे...",
success: "रिपोर्ट यशस्वीरित्या सबमिट झाला",
successDesc: "शहर स्वच्छ ठेवण्यासाठी मदत केल्याबद्दल धन्यवाद!",
fail: "सबमिशन अयशस्वी",
error: "काहीतरी चूक झाली",
serverError: "सर्व्हर त्रुटी",
serverErrorDesc: "रिपोर्ट सबमिट करता आला नाही",
myDashboard: "माझा डॅशबोर्ड",
coins: "मिळालेले कॉइन्स",
submitted: "सबमिट केलेल्या रिपोर्ट्स",
completed: "पूर्ण झालेल्या रिपोर्ट्स",
rewards: "रिवॉर्ड मिळवा",
redeem: "रिडीम करा आणि सर्टिफिकेट डाउनलोड करा",
loginFirst: "कृपया आधी लॉगिन करा",
notEnoughCoins: "पुरेसे कॉइन्स नाहीत",
redeemed: "रिवॉर्ड यशस्वीरित्या मिळाला"
  },

  gu: {
    home: "હોમ",
    recycling: "રીસાયક્લિંગ",
    report: "રિપોર્ટ",
    about: "વિશે",
    myReports: "મારા રિપોર્ટ્સ",
    login: "લોગિન",
    signup: "સાઇન અપ",
    logout: "લોગઆઉટ",
    welcome: "સ્વાગત",

    heroTitle:
      "સફાઈ કોઈ કાયદા દ્વારા લાદવામાં આવેલી ફરજ નથી, પરંતુ સમાજ પ્રત્યે આપણી જવાબદારી છે.",
    heroSubtitle:
      "આજનું નાનું પગલું આવતીકાલે સ્વચ્છ દુનિયા બનાવે છે.",
    recycleBtn: "રીસાયક્લિંગ આઈડિયા",
    reportBtn: "રિપોર્ટ",
    reportTitle: "કચરો સમસ્યા રિપોર્ટ કરો",
binId: "ડસ્ટબિન આઈડી",
issueType: "સમस्या પ્રકાર",
selectIssue: "સમસા પસંદ કરો",
selectIssueDesc: "કૃપા કરીને સમસ્યા પસંદ કરો",
illegal: "ગેરકાયદેસર કચરો ફેંકવો",
overflow: "ભરાયેલ ડસ્ટબિન",
damaged: "તૂટેલું ડસ્ટબિન",
location: "GPS સ્થાન",
phone: "સંપર્ક નંબર",
phonePlaceholder: "ફોન નંબર દાખલ કરો",
descPlaceholder: "સમસ્યા વર્ણવો...",
upload: "ફોટો અપલોડ કરો",
submit: "રિપોર્ટ સબમિટ કરો",
submitting: "સબમિટ થઈ રહ્યું છે...",
success: "રિપોર્ટ સફળતાપૂર્વક સબમિટ થયો",
successDesc: "શહેર સ્વચ્છ રાખવામાં મદદ માટે આભાર!",
fail: "સબમિશન નિષ્ફળ",
error: "કઈક ખોટું થયું",
serverError: "સર્વર ભૂલ",
serverErrorDesc: "રિપોર્ટ મોકલી શકાયો નહીં",
myDashboard: "મારું ડેશબોર્ડ",
coins: "મેળવેલા કોઇન્સ",
submitted: "સબમિટ કરેલી રિપોર્ટ્સ",
completed: "પૂર્ણ થયેલી રિપોર્ટ્સ",
rewards: "રિવોર્ડ મેળવો",
redeem: "રિડીમ કરો અને સર્ટિફિકેટ ડાઉનલોડ કરો",
loginFirst: "કૃપા કરીને પહેલા લોગિન કરો",
notEnoughCoins: "પર્યાપ્ત કોઇન્સ નથી",
redeemed: "રિવોર્ડ સફળતાપૂર્વક મેળવ્યો"
  },

  kn: {
    home: "ಹೋಮ್",
    recycling: "ರಿಸೈಕ್ಲಿಂಗ್",
    report: "ವರದಿ",
    about: "ಬಗ್ಗೆ",
    myReports: "ನನ್ನ ವರದಿಗಳು",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    logout: "ಲಾಗೌಟ್",
    welcome: "ಸ್ವಾಗತ",

    heroTitle:
      "ಸ್ವಚ್ಛತೆ ಕಾನೂನು ಹೇರಿದ ಕರ್ತವ್ಯವಲ್ಲ, ಸಮಾಜದ ಪ್ರತಿಯೊಬ್ಬರ ಜವಾಬ್ದಾರಿ.",
    heroSubtitle:
      "ಇಂದು ಮಾಡಿದ ಸಣ್ಣ ಕೆಲಸ ನಾಳೆ ಸ್ವಚ್ಛ ಲೋಕವನ್ನು ನಿರ್ಮಿಸುತ್ತದೆ.",

    recycleBtn: "ರಿಸೈಕ್ಲಿಂಗ್ ಐಡಿಯಾಸ್",
    reportBtn: "ವರದಿ",

    reportTitle: "ತ್ಯಾಜ್ಯ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    binId: "ಡಸ್ಟ್‌ಬಿನ್ ಐಡಿ",
    issueType: "ಸಮಸ್ಯೆಯ ಪ್ರಕಾರ",
    selectIssue: "ಸಮಸ್ಯೆ ಆಯ್ಕೆಮಾಡಿ",
    selectIssueDesc: "ದಯವಿಟ್ಟು ಸಮಸ್ಯೆಯ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",

    illegal: "ಅಕ್ರಮವಾಗಿ ಕಸ ತ್ಯಜಿಸುವುದು",
    overflow: "ಪೂರ್ಣವಾದ ಡಸ್ಟ್‌ಬಿನ್",
    damaged: "ಹಾನಿಗೊಂಡ ಡಸ್ಟ್‌ಬಿನ್",

    location: "GPS ಸ್ಥಳ",
    phone: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
    phonePlaceholder: "ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    descPlaceholder: "ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ...",

    upload: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    submit: "ವರದಿ ಸಲ್ಲಿಸಿ",
    submitting: "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    success: "ವರದಿ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    successDesc: "ನಗರವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಲು ಸಹಾಯ ಮಾಡಿದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು!",

    fail: "ಸಲ್ಲಿಕೆ ವಿಫಲವಾಗಿದೆ",
    error: "ಏನೋ ತಪ್ಪಾಗಿದೆ",
    serverError: "ಸರ್ವರ್ ದೋಷ",
    serverErrorDesc: "ವರದಿ ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",

    myDashboard: "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    coins: "ಪಡೆಯಲಾದ ನಾಣ್ಯಗಳು",
    submitted: "ಸಲ್ಲಿಸಿದ ವರದಿಗಳು",
    completed: "ಪೂರ್ಣಗೊಂಡ ವರದಿಗಳು",
    rewards: "ಬಹುಮಾನಗಳನ್ನು ಪಡೆಯಿರಿ",
    redeem: "ರೀಡೀಮ್ ಮಾಡಿ ಪ್ರಮಾಣಪತ್ರ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    loginFirst: "ದಯವಿಟ್ಟು ಮೊದಲು ಲಾಗಿನ್ ಮಾಡಿ",
    notEnoughCoins: "ಸಾಕಷ್ಟು ನಾಣ್ಯಗಳಿಲ್ಲ",
    redeemed: "ಬಹುಮಾನ ಯಶಸ್ವಿಯಾಗಿ ಪಡೆದಿದೆ"
  },

  ml: {
    home: "ഹോം",
    recycling: "റിസൈക്ലിംഗ്",
    report: "റിപ്പോർട്ട്",
    about: "കുറിച്ച്",
    myReports: "എന്റെ റിപ്പോർട്ടുകൾ",
    login: "ലോഗിൻ",
    signup: "സൈൻ അപ്പ്",
    logout: "ലോഗൗട്ട്",
    welcome: "സ്വാഗതം",

    heroTitle:
      "ശുചിത്വം നിയമം നിർബന്ധിതമാക്കിയ കടമയല്ല, സമൂഹത്തോടുള്ള ഉത്തരവാദിത്തമാണ്.",
    heroSubtitle:
      "ഇന്നത്തെ ചെറിയ പ്രവർത്തനം നാളെയെ ശുചിയാക്കും.",
    recycleBtn: "റിസൈക്ലിംഗ് ആശയങ്ങൾ",
    reportBtn: "റിപ്പോർട്ട്",
    reportTitle: "മാലിന്യ പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
binId: "ഡസ്റ്റ്‌ബിൻ ഐഡി",
issueType: "പ്രശ്നത്തിന്റെ തരം",
selectIssue: "പ്രശ്നം തിരഞ്ഞെടുക്കുക",
selectIssueDesc: "ദയവായി പ്രശ്നത്തിന്റെ തരം തിരഞ്ഞെടുക്കുക",
illegal: "നിയമവിരുദ്ധമായി മാലിന്യം ഇടൽ",
overflow: "നിറഞ്ഞ ഡസ്റ്റ്‌ബിൻ",
damaged: "നശിച്ച ഡസ്റ്റ്‌ബിൻ",
location: "GPS സ്ഥലം",
phone: "ഫോൺ നമ്പർ",
phonePlaceholder: "ഫോൺ നമ്പർ നൽകുക",
descPlaceholder: "പ്രശ്നം വിശദീകരിക്കുക...",
upload: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
submit: "റിപ്പോർട്ട് സമർപ്പിക്കുക",
submitting: "സമർപ്പിക്കുന്നു...",
success: "റിപ്പോർട്ട് വിജയകരമായി സമർപ്പിച്ചു",
successDesc: "നഗരം ശുചിയായി നിലനിർത്താൻ സഹായിച്ചതിന് നന്ദി!",
fail: "സമർപ്പിക്കൽ പരാജയപ്പെട്ടു",
error: "എന്തോ പിഴവ് സംഭവിച്ചു",
serverError: "സർവർ പിശക്",
serverErrorDesc: "റിപ്പോർട്ട് അയയ്ക്കാൻ കഴിഞ്ഞില്ല",
myDashboard: "എന്റെ ഡാഷ്ബോർഡ്",
coins: "നേടിയ നാണയങ്ങൾ",
submitted: "സമർപ്പിച്ച റിപ്പോർട്ടുകൾ",
completed: "പൂർത്തിയായ റിപ്പോർട്ടുകൾ",
rewards: "റിവാർഡുകൾ നേടുക",
redeem: "റീഡീം ചെയ്ത് സർട്ടിഫിക്കറ്റ് ഡൗൺലോഡ് ചെയ്യുക",
loginFirst: "ദയവായി ആദ്യം ലോഗിൻ ചെയ്യുക",
notEnoughCoins: "മതിയായ നാണയങ്ങൾ ഇല്ല",
redeemed: "റിവാർഡ് വിജയകരമായി ലഭിച്ചു"
  },

  pa: {
    home: "ਹੋਮ",
    recycling: "ਰੀਸਾਈਕਲਿੰਗ",
    report: "ਰਿਪੋਰਟ",
    about: "ਬਾਰੇ",
    myReports: "ਮੇਰੀ ਰਿਪੋਰਟਾਂ",
    login: "ਲਾਗਇਨ",
    signup: "ਸਾਇਨ ਅੱਪ",
    logout: "ਲਾਗਆਉਟ",
    welcome: "ਸਵਾਗਤ",

    heroTitle:
      "ਸਫਾਈ ਕੋਈ ਕਾਨੂੰਨ ਦੁਆਰਾ ਲਾਗੂ ਕੀਤੀ ਜ਼ਿੰਮੇਵਾਰੀ ਨਹੀਂ, ਸਗੋਂ ਸਮਾਜ ਪ੍ਰਤੀ ਸਾਡੀ ਜ਼ਿੰਮੇਵਾਰੀ ਹੈ।",
    heroSubtitle:
      "ਅੱਜ ਦੀ ਛੋਟੀ ਕੋਸ਼ਿਸ਼ ਕੱਲ੍ਹ ਨੂੰ ਸਾਫ ਬਣਾਉਂਦੀ ਹੈ।",
    recycleBtn: "ਰੀਸਾਈਕਲਿੰਗ ਆਈਡੀਆਜ਼",
    reportBtn: "ਰਿਪੋਰਟ",
    reportTitle: "ਕੂੜਾ ਸਮੱਸਿਆ ਰਿਪੋਰਟ ਕਰੋ",
binId: "ਡਸਟਬਿਨ ਆਈਡੀ",
issueType: "ਸਮੱਸਿਆ ਦੀ ਕਿਸਮ",
selectIssue: "ਸਮੱਸਿਆ ਚੁਣੋ",
selectIssueDesc: "ਕਿਰਪਾ ਕਰਕੇ ਸਮੱਸਿਆ ਦੀ ਕਿਸਮ ਚੁਣੋ",
illegal: "ਗੈਰਕਾਨੂੰਨੀ ਕੂੜਾ ਸੁੱਟਣਾ",
overflow: "ਭਰਿਆ ਹੋਇਆ ਡਸਟਬਿਨ",
damaged: "ਟੁੱਟਿਆ ਹੋਇਆ ਡਸਟਬਿਨ",
location: "GPS ਸਥਾਨ",
phone: "ਸੰਪਰਕ ਨੰਬਰ",
phonePlaceholder: "ਫੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
descPlaceholder: "ਸਮੱਸਿਆ ਦਾ ਵੇਰਵਾ ਦਿਓ...",
upload: "ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ",
submit: "ਰਿਪੋਰਟ ਭੇਜੋ",
submitting: "ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
success: "ਰਿਪੋਰਟ ਸਫਲਤਾਪੂਰਵਕ ਭੇਜੀ ਗਈ",
successDesc: "ਸ਼ਹਿਰ ਨੂੰ ਸਾਫ ਰੱਖਣ ਲਈ ਧੰਨਵਾਦ!",
fail: "ਸਬਮਿਸ਼ਨ ਅਸਫਲ",
error: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ",
serverError: "ਸਰਵਰ ਗਲਤੀ",
serverErrorDesc: "ਰਿਪੋਰਟ ਭੇਜਣ ਵਿੱਚ ਅਸਮਰੱਥ",
myDashboard: "ਮੇਰਾ ਡੈਸ਼ਬੋਰਡ",
coins: "ਕਮਾਏ ਗਏ ਕੋਇਨ",
submitted: "ਜਮ੍ਹਾਂ ਕੀਤੀਆਂ ਰਿਪੋਰਟਾਂ",
completed: "ਪੂਰੀਆਂ ਹੋਈਆਂ ਰਿਪੋਰਟਾਂ",
rewards: "ਇਨਾਮ ਪ੍ਰਾਪਤ ਕਰੋ",
redeem: "ਰੀਡੀਮ ਕਰੋ ਅਤੇ ਸਰਟੀਫਿਕੇਟ ਡਾਊਨਲੋਡ ਕਰੋ",
loginFirst: "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਲਾਗਇਨ ਕਰੋ",
notEnoughCoins: "ਪੂਰੇ ਕੋਇਨ ਨਹੀਂ ਹਨ",
redeemed: "ਇਨਾਮ ਸਫਲਤਾਪੂਰਵਕ ਪ੍ਰਾਪਤ ਕੀਤਾ ਗਿਆ"
  }
};



export default langData;